### ISSUE TITLE
Implement `build` command parsing for Docker Image

### ISSUE THREAD

**Issue by botchniaque** [zalando/pazuzu#8]
Define syntax (how to pass parameters)

### Some ideas:
- `pazuzu build -f feature1 -f feature2`
- `pazuzu build -f feature1,feature2`
- `pazuzu build -f feature1 feature2`
- Interactive interface `pazuzu build` 

### Skip image building option
- `--dry-run`
- `--only-dockerfile`

**Comment by pgronkiewicz** [comment]
Default name of the tool should be "pazuzu" and it should support both passing a list of features and a file with them (-f makes more sense for file, for a list maybe -l ?)

Additional thing to remember about syntax is that it should support tagging and then also pushing

**Comment by botchniaque** [comment]
Wasn't tagging and pushing supposed to be responsibilities of the *Docker Maker* (that not yet existing part?)

**Comment by pgronkiewicz** [comment]
The Docker Maker part would be mostly an orchestrator, the CLI should at least tag the image, so it can be easily pushed and identified (it should be optional parameter, by default it would return the id of built image)

**Comment by botchniaque** [comment]
Is *tagging* going to be used to support image versioning?

**Comment by mikkeloscar** [comment]
@pgronkiewicz 

> Additional thing to remember about syntax is that it should support tagging and then also pushing

What do you mean by tag? Is it a docker tag or a tag on the pazuzu features?

For pushing, that would basically be `docker push` right, or am I missing something?
